# Generated by Django 4.1.3 on 2022-11-21 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('gov_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=99)),
                ('second_name', models.CharField(max_length=99)),
                ('username', models.CharField(max_length=99)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesurable_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('mesurable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.mesurable')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.part')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Размещён', 'Размещён')], max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.jobprice')),
                ('parts_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.partsprice')),
            ],
        ),
        migrations.AddField(
            model_name='jobprice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.jobtype'),
        ),
        migrations.AddField(
            model_name='jobprice',
            name='mesurable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.mesurable'),
        ),
        migrations.CreateModel(
            name='ClintAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.auto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.client')),
            ],
        ),
    ]
