# Generated by Django 4.1.3 on 2022-11-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClintAuto',
            new_name='ClientAuto',
        ),
    ]
