# Generated by Django 4.1.3 on 2022-11-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_jobprice_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='gov_number',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='clientauto',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.auto', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='clientauto',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='jobprice',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='jobprice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.jobtype', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='jobprice',
            name='mesurable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.mesurable', verbose_name='Измерение'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='job_name',
            field=models.CharField(max_length=100, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='mesurable',
            name='mesurable_name',
            field=models.CharField(max_length=100, verbose_name='Название измерения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.jobprice', verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='parts_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.partsprice', verbose_name='Цена детали'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Размещён', 'Размещён')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=100, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='partsprice',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='partsprice',
            name='mesurable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.mesurable', verbose_name='Измерение'),
        ),
        migrations.AlterField(
            model_name='partsprice',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.part', verbose_name='Деталь'),
        ),
    ]
