# Generated by Django 4.1.3 on 2022-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_order_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
