# Generated by Django 4.1.3 on 2022-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_partsprice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
