# Generated by Django 4.1.3 on 2022-11-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_alter_partsprice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=100, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('mesurable', models.IntegerField(verbose_name='Измерение')),
                ('total', models.IntegerField(verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.order', verbose_name='Заказ')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.paymenttype', verbose_name='Тип оплаты')),
            ],
        ),
    ]
