# Generated by Django 4.1.3 on 2022-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_paymenttype_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
