# Generated by Django 4.1.3 on 2022-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_jobtype_description_jobtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
