# Generated by Django 4.1.3 on 2022-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_partsprice_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='job',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'В работе'), ('1', 'Ожидает оплаты'), ('2', 'Размещён')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='job',
            field=models.ManyToManyField(to='mainsite.jobprice', verbose_name='Работа'),
        ),
    ]
