# Generated by Django 4.1.3 on 2022-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_remove_order_job_alter_order_status_order_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='job',
            field=models.ManyToManyField(to='mainsite.jobtype', verbose_name='Работа'),
        ),
    ]
