# Generated by Django 4.1.3 on 2022-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_joblist_alter_order_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='job',
        ),
        migrations.AddField(
            model_name='order',
            name='job_list',
            field=models.ManyToManyField(to='mainsite.jobtype'),
        ),
        migrations.DeleteModel(
            name='JobList',
        ),
    ]
