# Generated by Django 4.1.3 on 2022-11-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_remove_order_job_order_job_list_delete_joblist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts_price',
        ),
    ]
