# Generated by Django 4.1.3 on 2022-11-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_remove_order_parts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='mesurable',
        ),
    ]
