# Generated by Django 4.1.3 on 2022-12-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_remove_bill_mesurable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.clientauto', verbose_name='Машина клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='job_list',
            field=models.ManyToManyField(blank=True, null=True, to='mainsite.jobtype'),
        ),
    ]
